// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAca7UaS1jEMC_BVy1gob_oOeDTWZMbxrY',
    appId: '1:1026173649632:web:84ee7446770a31c1978685',
    messagingSenderId: '1026173649632',
    projectId: 's6xbper8boaoqr7t8y9f22ln48uoef',
    authDomain: 's6xbper8boaoqr7t8y9f22ln48uoef.firebaseapp.com',
    storageBucket: 's6xbper8boaoqr7t8y9f22ln48uoef.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiunEkcDLs2Sv9qPJaZOlOot3yRy64stI',
    appId: '1:1026173649632:android:44e2418052355501978685',
    messagingSenderId: '1026173649632',
    projectId: 's6xbper8boaoqr7t8y9f22ln48uoef',
    storageBucket: 's6xbper8boaoqr7t8y9f22ln48uoef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAmZS4zbkfwjgdumYj8PKGXAuoeeuW0YU',
    appId: '1:1026173649632:ios:f9d1e10819826304978685',
    messagingSenderId: '1026173649632',
    projectId: 's6xbper8boaoqr7t8y9f22ln48uoef',
    storageBucket: 's6xbper8boaoqr7t8y9f22ln48uoef.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
